# Generated by Django 6.0 on 2026-06-03 07:28

import django.db.models.deletion
import pgvector.django
import pgvector.django.indexes
import pgvector.django.vector
import webapps.vanna.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('oracle', 'Oracle')], max_length=20)),
                ('db_profile', models.CharField(blank=True, default='', max_length=120)),
                ('default_schema', models.CharField(blank=True, default='', max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('execute_enabled', models.BooleanField(default=False)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nl2sql_data_source',
                'indexes': [models.Index(fields=['db_type', 'enabled'], name='nl2sql_data_db_type_c4c75d_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=128)),
                ('question', models.TextField()),
                ('normalized_question', models.TextField(blank=True, default='')),
                ('retrieved_context_json', models.JSONField(blank=True, default=dict)),
                ('generated_sql', models.TextField(blank=True, default='')),
                ('cleaned_sql', models.TextField(blank=True, default='')),
                ('guard_status', models.CharField(blank=True, default='', max_length=32)),
                ('guard_message', models.TextField(blank=True, default='')),
                ('guard_rules_json', models.JSONField(blank=True, default=list)),
                ('final_sql', models.TextField(blank=True, default='')),
                ('execution_status', models.CharField(blank=True, default='', max_length=32)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('engine_version', models.CharField(blank=True, default='', max_length=80)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=80)),
                ('guard_version', models.CharField(blank=True, default='', max_length=80)),
                ('retriever_version', models.CharField(blank=True, default='', max_length=80)),
                ('vanna_version', models.CharField(blank=True, default='', max_length=80)),
                ('vanna_training_version', models.CharField(blank=True, default='', max_length=80)),
                ('vanna_response_json', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, default='', max_length=160)),
                ('model_parameters_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to='vanna_integration.datasource')),
            ],
            options={
                'db_table': 'nl2sql_query_log',
            },
        ),
        migrations.CreateModel(
            name='ReviewQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='')),
                ('suggested_sql', models.TextField(blank=True, default='')),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vanna_integration.querylog')),
            ],
            options={
                'db_table': 'nl2sql_review_queue',
            },
        ),
        migrations.CreateModel(
            name='SchemaObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=120)),
                ('object_name', models.CharField(max_length=160)),
                ('object_type', models.CharField(choices=[('table', 'Table'), ('view', 'View'), ('materialized_view', 'Materialized View')], max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('columns_json', models.JSONField(blank=True, default=list)),
                ('ddl_text', models.TextField(blank=True, default='')),
                ('row_estimate', models.BigIntegerField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_objects', to='vanna_integration.datasource')),
            ],
            options={
                'db_table': 'nl2sql_schema_object',
            },
        ),
        migrations.CreateModel(
            name='SchemaEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(choices=[('ddl', 'DDL'), ('columns', 'Columns'), ('documentation', 'Documentation')], max_length=32)),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=160)),
                ('embedding_dimension', models.PositiveIntegerField(default=webapps.vanna.models._embedding_dimensions)),
                ('content_hash', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schema_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='vanna_integration.schemaobject')),
            ],
            options={
                'db_table': 'nl2sql_schema_embedding',
            },
        ),
        migrations.CreateModel(
            name='TablePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=120)),
                ('table_name', models.CharField(max_length=160)),
                ('is_allowed', models.BooleanField(default=True)),
                ('requires_where', models.BooleanField(default=False)),
                ('max_row_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_policies', to='vanna_integration.datasource')),
            ],
            options={
                'db_table': 'nl2sql_table_policy',
            },
        ),
        migrations.CreateModel(
            name='TrainingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('sql_text', models.TextField()),
                ('dialect', models.CharField(blank=True, default='', max_length=32)),
                ('tags_json', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_by', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_examples', to='vanna_integration.datasource')),
            ],
            options={
                'db_table': 'nl2sql_training_example',
            },
        ),
        migrations.CreateModel(
            name='ExampleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('sql_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=160)),
                ('embedding_dimension', models.PositiveIntegerField(default=webapps.vanna.models._embedding_dimensions)),
                ('content_hash', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_embeddings', to='vanna_integration.datasource')),
                ('training_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='vanna_integration.trainingexample')),
            ],
            options={
                'db_table': 'nl2sql_example_embedding',
            },
        ),
        migrations.CreateModel(
            name='UserDataSourceAcl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('can_generate', models.BooleanField(default=True)),
                ('can_execute', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_acls', to='vanna_integration.datasource')),
            ],
            options={
                'db_table': 'nl2sql_user_data_source_acl',
            },
        ),
        migrations.CreateModel(
            name='VannaTrainingSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('ddl', 'DDL'), ('documentation', 'Documentation'), ('example', 'Example')], max_length=32)),
                ('source_object_id', models.BigIntegerField(blank=True, null=True)),
                ('vanna_training_id', models.CharField(blank=True, default='', max_length=160)),
                ('content_hash', models.CharField(blank=True, default='', max_length=128)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanna_training_syncs', to='vanna_integration.datasource')),
            ],
            options={
                'db_table': 'nl2sql_vanna_training_sync',
            },
        ),
        migrations.CreateModel(
            name='ColumnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=120)),
                ('table_name', models.CharField(max_length=160)),
                ('column_name', models.CharField(max_length=160)),
                ('is_allowed', models.BooleanField(default=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('mask_type', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_policies', to='vanna_integration.datasource')),
            ],
            options={
                'db_table': 'nl2sql_column_policy',
                'constraints': [models.UniqueConstraint(fields=('data_source', 'schema_name', 'table_name', 'column_name'), name='uq_nl2sql_column_policy')],
            },
        ),
        migrations.CreateModel(
            name='BusinessTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('mapped_schema', models.CharField(blank=True, default='', max_length=120)),
                ('mapped_tables_json', models.JSONField(blank=True, default=list)),
                ('mapped_columns_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_terms', to='vanna_integration.datasource')),
            ],
            options={
                'db_table': 'nl2sql_business_term',
                'indexes': [models.Index(fields=['data_source', 'term'], name='nl2sql_busi_data_so_de4f39_idx')],
                'constraints': [models.UniqueConstraint(fields=('data_source', 'term'), name='uq_nl2sql_business_term')],
            },
        ),
        migrations.CreateModel(
            name='EvalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('expected_sql', models.TextField(blank=True, default='')),
                ('expected_tables_json', models.JSONField(blank=True, default=list)),
                ('expected_columns_json', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_cases', to='vanna_integration.datasource')),
            ],
            options={
                'db_table': 'nl2sql_eval_case',
                'indexes': [models.Index(fields=['data_source', 'enabled'], name='nl2sql_eval_data_so_e703d9_idx'), models.Index(fields=['difficulty', 'category'], name='nl2sql_eval_difficu_fe6bc1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['data_source', 'created_at'], name='nl2sql_quer_data_so_3077a3_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['user_id', 'created_at'], name='nl2sql_quer_user_id_709169_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['guard_status'], name='nl2sql_quer_guard_s_cf3db5_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['execution_status'], name='nl2sql_quer_executi_4f494a_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewqueue',
            index=models.Index(fields=['review_status', 'created_at'], name='nl2sql_revi_review__254761_idx'),
        ),
        migrations.AddIndex(
            model_name='schemaobject',
            index=models.Index(fields=['data_source', 'is_enabled'], name='nl2sql_sche_data_so_27c703_idx'),
        ),
        migrations.AddIndex(
            model_name='schemaobject',
            index=models.Index(fields=['schema_name', 'object_name'], name='nl2sql_sche_schema__50e3dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='schemaobject',
            constraint=models.UniqueConstraint(fields=('data_source', 'schema_name', 'object_name'), name='uq_nl2sql_schema_object'),
        ),
        migrations.AddIndex(
            model_name='schemaembedding',
            index=models.Index(fields=['schema_object', 'chunk_type'], name='nl2sql_sche_schema__9dd8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='schemaembedding',
            index=models.Index(fields=['content_hash'], name='nl2sql_sche_content_b7a8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='schemaembedding',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='nl2sql_schema_vec_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='tablepolicy',
            constraint=models.UniqueConstraint(fields=('data_source', 'schema_name', 'table_name'), name='uq_nl2sql_table_policy'),
        ),
        migrations.AddIndex(
            model_name='trainingexample',
            index=models.Index(fields=['data_source', 'review_status'], name='nl2sql_trai_data_so_3d28e8_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingexample',
            index=models.Index(fields=['created_at'], name='nl2sql_trai_created_ac18eb_idx'),
        ),
        migrations.AddIndex(
            model_name='exampleembedding',
            index=models.Index(fields=['data_source'], name='nl2sql_exam_data_so_939b44_idx'),
        ),
        migrations.AddIndex(
            model_name='exampleembedding',
            index=models.Index(fields=['content_hash'], name='nl2sql_exam_content_873621_idx'),
        ),
        migrations.AddIndex(
            model_name='exampleembedding',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='nl2sql_example_vec_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='userdatasourceacl',
            constraint=models.UniqueConstraint(fields=('user_id', 'data_source'), name='uq_nl2sql_user_data_source_acl'),
        ),
        migrations.AddIndex(
            model_name='vannatrainingsync',
            index=models.Index(fields=['data_source', 'sync_type', 'sync_status'], name='nl2sql_vann_data_so_b98187_idx'),
        ),
        migrations.AddIndex(
            model_name='vannatrainingsync',
            index=models.Index(fields=['content_hash'], name='nl2sql_vann_content_7333a2_idx'),
        ),
    ]
