# Generated by Django 6.0 on 2026-06-11 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanna_integration', '0002_nl2sql_embedding_dim_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedQueryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='自然語言提問')),
                ('failed_sql', models.TextField(verbose_name='失敗之 SQL')),
                ('error_message', models.TextField(verbose_name='錯誤訊息')),
                ('data_source_code', models.CharField(blank=True, default='', max_length=80, verbose_name='資料來源編號')),
                ('analysis', models.TextField(blank=True, default='', verbose_name='失敗根因剖析')),
                ('action_taken', models.TextField(blank=True, default='', verbose_name='精進措施 (如修正 DDL/新增 SQL 範例)')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('optimized', '已完成優化'), ('ignored', '忽略/不處理')], default='pending', max_length=30, verbose_name='處理狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='failed_record', to='vanna_integration.querylog', verbose_name='關聯查詢日誌')),
            ],
            options={
                'verbose_name': '失敗語法精進記錄',
                'db_table': 'nl2sql_failed_query_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
