# Generated by Django 6.0 on 2026-06-17 05:38

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import webapps.vanna.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanna_integration', '0003_failedqueryrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('documentation', models.TextField()),
                ('created_by', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_documentations', to='vanna_integration.datasource')),
            ],
            options={
                'db_table': 'nl2sql_training_documentation',
            },
        ),
        migrations.CreateModel(
            name='DocumentationEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('documentation_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=160)),
                ('embedding_dimension', models.PositiveIntegerField(default=webapps.vanna.models._embedding_dimensions)),
                ('content_hash', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_embeddings', to='vanna_integration.datasource')),
                ('training_documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='vanna_integration.trainingdocumentation')),
            ],
            options={
                'db_table': 'nl2sql_documentation_embedding',
            },
        ),
        migrations.AddIndex(
            model_name='trainingdocumentation',
            index=models.Index(fields=['data_source'], name='nl2sql_trai_data_so_c70852_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingdocumentation',
            index=models.Index(fields=['created_at'], name='nl2sql_trai_created_423204_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationembedding',
            index=models.Index(fields=['data_source'], name='nl2sql_docu_data_so_397540_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationembedding',
            index=models.Index(fields=['content_hash'], name='nl2sql_docu_content_ea40c7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationembedding',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='nl2sql_doc_vec_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
