from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

from pptx import Presentation
from pptx.util import Pt

from webapps.text2pptx.pptx2schema.models.bundle import PresentationBundle
from webapps.text2pptx.pptx2schema.renderers.text_fit import clamp_text


def _pick_layout(prs: Presentation, fallback_index: int) -> Any:
    if 0 <= fallback_index < len(prs.slide_layouts):
        return prs.slide_layouts[fallback_index]
    return prs.slide_layouts[0]


def render_bundle_to_pptx(bundle: PresentationBundle, content: Dict[str, Any], output_path: str | Path) -> None:
    prs = Presentation()
    cover = prs.slides.add_slide(_pick_layout(prs, 0))
    title = str(content.get("main_title") or "重建簡報")
    subtitle = str(content.get("main_subtitle") or "Generated by pptx2schema")
    if cover.shapes.title:
        cover.shapes.title.text = title
        cover.shapes.title.text_frame.paragraphs[0].font.size = Pt(32)
    if len(cover.placeholders) > 1:
        cover.placeholders[1].text = subtitle

    slides = content.get("slides") or []
    if not isinstance(slides, list):
        slides = []

    for item in slides:
        if not isinstance(item, dict):
            continue
        slide = prs.slides.add_slide(_pick_layout(prs, 1))
        ttl = str(item.get("title") or "").strip() or "投影片"
        bullets = item.get("bullets") or []
        if not isinstance(bullets, list):
            bullets = [str(bullets)]
        if slide.shapes.title:
            slide.shapes.title.text = ttl
        body = None
        for ph in slide.placeholders:
            if ph == slide.shapes.title:
                continue
            if getattr(ph, "has_text_frame", False):
                body = ph.text_frame
                break
        if body is None:
            continue
        body.clear()
        for i, b in enumerate(bullets):
            p = body.paragraphs[0] if i == 0 else body.add_paragraph()
            p.text = clamp_text(str(b), max_chars=280)

    prs.save(str(output_path))
