SAMPLE_QUESTIONS = [
    {"question": "數位孿生在製造業的核心價值是什麼？", "expected_keywords": ["數位孿生", "製造業"], "twin_level": "Level 5", "isa95_level": "Level 4", "expected_answer_type": "concept"},
    {"question": "ISA-95 Level 3 通常對應哪些系統？", "expected_keywords": ["ISA-95", "MES", "CIM"], "twin_level": "Level 3", "isa95_level": "Level 3", "expected_answer_type": "classification"},
    {"question": "MES 在數位孿生架構中屬於哪一層？", "expected_keywords": ["MES", "資料整合層"], "twin_level": "Level 3", "isa95_level": "Level 3", "expected_answer_type": "classification"},
    {"question": "ERP 與 APS 在決策優化層扮演什麼角色？", "expected_keywords": ["ERP", "APS", "決策優化"], "twin_level": "Level 5", "isa95_level": "Level 4", "expected_answer_type": "explanation"},
    {"question": "SCADA 與 PLC 的資料如何支援數位孿生？", "expected_keywords": ["SCADA", "PLC", "資料擷取"], "twin_level": "Level 2", "isa95_level": "Level 2", "expected_answer_type": "explanation"},
    {"question": "不使用無線 IoT 時，產線資料擷取可採哪些方式？", "expected_keywords": ["有線", "OPC UA", "Modbus"], "twin_level": "Level 2", "isa95_level": "Level 1", "expected_answer_type": "architecture"},
    {"question": "軍工產線導入數位孿生時需注意哪些資安要求？", "expected_keywords": ["軍工", "資安", "內網"], "twin_level": "Level 5", "isa95_level": "Level 4", "expected_answer_type": "security"},
    {"question": "FMEA 如何與數位孿生風險模型整合？", "expected_keywords": ["FMEA", "風險"], "twin_level": "Level 4", "isa95_level": "Level 3", "expected_answer_type": "method"},
    {"question": "RCA 報告如何轉成知識節點？", "expected_keywords": ["RCA", "知識節點"], "twin_level": "Level 4", "isa95_level": "Level 3", "expected_answer_type": "method"},
    {"question": "預測性維護需要哪些資料來源？", "expected_keywords": ["預測性維護", "感測器", "維修紀錄"], "twin_level": "Level 5", "isa95_level": "Level 3", "expected_answer_type": "data_requirement"},
    {"question": "如何設計機敏文件的 security_level？", "expected_keywords": ["security_level", "權限"], "twin_level": "Level 5", "isa95_level": "Level 4", "expected_answer_type": "security"},
    {"question": "pgvector 在 RAG 系統中負責什麼？", "expected_keywords": ["pgvector", "RAG", "向量檢索"], "twin_level": "Level 5", "isa95_level": "Level 4", "expected_answer_type": "technical"},
    {"question": "資料治理在 Level 3 的重要性是什麼？", "expected_keywords": ["資料治理", "Level 3"], "twin_level": "Level 3", "isa95_level": "Level 3", "expected_answer_type": "explanation"},
    {"question": "工業 4.0 與數位孿生有何關聯？", "expected_keywords": ["工業 4.0", "數位孿生"], "twin_level": "Level 5", "isa95_level": "Level 4", "expected_answer_type": "concept"},
    {"question": "CIM 在軍工產線中可整合哪些製造資料？", "expected_keywords": ["CIM", "製造資料"], "twin_level": "Level 3", "isa95_level": "Level 3", "expected_answer_type": "classification"},
    {"question": "QMS 資料如何支援品質模型？", "expected_keywords": ["QMS", "品質模型"], "twin_level": "Level 4", "isa95_level": "Level 3", "expected_answer_type": "explanation"},
    {"question": "WMS 與批號追溯如何支援數位孿生？", "expected_keywords": ["WMS", "追溯"], "twin_level": "Level 3", "isa95_level": "Level 3", "expected_answer_type": "explanation"},
    {"question": "CMMS 維修紀錄如何用於預測性維護？", "expected_keywords": ["CMMS", "維修紀錄"], "twin_level": "Level 5", "isa95_level": "Level 3", "expected_answer_type": "method"},
    {"question": "如何用產能模型找出生產瓶頸？", "expected_keywords": ["產能模型", "瓶頸"], "twin_level": "Level 4", "isa95_level": "Level 3", "expected_answer_type": "method"},
    {"question": "封閉式內網如何部署 embedding 模型？", "expected_keywords": ["內網", "embedding"], "twin_level": "Level 5", "isa95_level": "Level 4", "expected_answer_type": "deployment"},
    {"question": "離線部署時如何處理 LLM 問答？", "expected_keywords": ["離線", "LLM", "Ollama"], "twin_level": "Level 5", "isa95_level": "Level 4", "expected_answer_type": "deployment"},
    {"question": "產線風險管理可如何建成 KnowledgeNode？", "expected_keywords": ["風險", "KnowledgeNode"], "twin_level": "Level 4", "isa95_level": "Level 3", "expected_answer_type": "method"},
    {"question": "Sensor 安裝位置屬於哪一個數位孿生層級？", "expected_keywords": ["Sensor", "安裝位置"], "twin_level": "Level 1", "isa95_level": "Level 1", "expected_answer_type": "classification"},
    {"question": "OPC UA 與 Modbus 在資料擷取層如何使用？", "expected_keywords": ["OPC UA", "Modbus"], "twin_level": "Level 2", "isa95_level": "Level 2", "expected_answer_type": "technical"},
    {"question": "如何依 security_level 過濾 RAG 檢索結果？", "expected_keywords": ["security_level", "RAG"], "twin_level": "Level 5", "isa95_level": "Level 4", "expected_answer_type": "technical"},
    {"question": "數位孿生成熟度可如何評估？", "expected_keywords": ["成熟度", "評估"], "twin_level": "Level 5", "isa95_level": "Level 4", "expected_answer_type": "assessment"},
    {"question": "資料清洗對 RAG 回答品質有何影響？", "expected_keywords": ["資料清洗", "RAG"], "twin_level": "Level 3", "isa95_level": "Level 3", "expected_answer_type": "explanation"},
    {"question": "如何把製程異常紀錄轉成 RCA 知識？", "expected_keywords": ["製程異常", "RCA"], "twin_level": "Level 4", "isa95_level": "Level 3", "expected_answer_type": "method"},
    {"question": "管理儀表板在數位孿生中屬於哪一層？", "expected_keywords": ["管理儀表板", "決策"], "twin_level": "Level 5", "isa95_level": "Level 4", "expected_answer_type": "classification"},
    {"question": "如何將 AI Agent 匯入文件後立即納入檢索？", "expected_keywords": ["AI Agent", "ingestion", "檢索"], "twin_level": "Level 5", "isa95_level": "Level 4", "expected_answer_type": "workflow"},
]
