from __future__ import annotations

from pathlib import Path

PROJECT_NAME = "pptx2schema"
SUPPORTED_EXTENSIONS = {".pptx"}
DEFAULT_RENDER_TITLE = "重建簡報"
DEFAULT_RENDER_SUBTITLE = "Generated by pptx2schema"

PACKAGE_ROOT = Path(__file__).resolve().parent
