from __future__ import annotations

from typing import Any, Dict, List


LEVEL_SETTINGS: Dict[str, Dict[str, Any]] = {
    "beginner": {
        "zh_label": "初級",
        "patterns": [
            {"kind": "statement", "en": "{subject_cap} usually {verb} {item} {place}.", "zh": "{subject_zh}通常會{verb_zh}{item_zh}。"},
            {"kind": "can_question", "en": "{modal_cap} {subject} {verb} {item} {closer}.", "zh": "{subject_zh}{closer_zh}{verb_zh}{item_zh}可以嗎？"},
            {"kind": "need_to", "en": "{subject_cap} need to {verb} {item} {time_phrase}.", "zh": "{subject_zh}需要在{time_phrase_zh}{verb_zh}{item_zh}。"},
            {"kind": "please", "en": "Please {verb} {item} {adverb}.", "zh": "請{adverb_zh}{verb_zh}{item_zh}。"},
            {"kind": "going_to", "en": "{subject_cap} am going to {verb} {item} later.", "zh": "{subject_zh}等一下要{verb_zh}{item_zh}。"},
            {"kind": "lets", "en": "Let's {verb} {item} together.", "zh": "我們一起{verb_zh}{item_zh}吧。"},
        ],
        "modals": [("Can", "今天", "today")],
        "adverbs": [("carefully", "仔細地")],
        "time_phrases": [("this morning", "今天早上")],
    },
    "intermediate": {
        "zh_label": "中級",
        "patterns": [
            {"kind": "statement", "en": "{subject_cap} often {verb} {item} {place}.", "zh": "{subject_zh}常常會{verb_zh}{item_zh}。"},
            {"kind": "would_like", "en": "{subject_cap} would like to {verb} {item} {closer}.", "zh": "{subject_zh}{closer_zh}想要{verb_zh}{item_zh}。"},
            {"kind": "have_to", "en": "{subject_cap} have to {verb} {item} {time_phrase}.", "zh": "{subject_zh}必須在{time_phrase_zh}{verb_zh}{item_zh}。"},
            {"kind": "could_you", "en": "Could you {verb} {item} {adverb}?", "zh": "你可以{adverb_zh}{verb_zh}{item_zh}嗎？"},
            {"kind": "because", "en": "{subject_cap} {verb} {item} because {reason}.", "zh": "{subject_zh}會{verb_zh}{item_zh}，因為{reason_zh}。"},
            {"kind": "how_long", "en": "How long does it take to {verb} {item}?", "zh": "要花多久才能{verb_zh}{item_zh}？"},
        ],
        "modals": [("Could", "這週", "this week")],
        "adverbs": [("efficiently", "有效率地")],
        "time_phrases": [("before lunch", "午餐前")],
    },
    "advanced": {
        "zh_label": "高級",
        "patterns": [
            {"kind": "wondering", "en": "{wondering_clause} {verb} {item} {closer}.", "zh": "{subject_zh}想知道是否可以{closer_zh}{verb_zh}{item_zh}。"},
            {"kind": "possible", "en": "Would it be possible to {verb} {item} {time_phrase}?", "zh": "是否有可能在{time_phrase_zh}{verb_zh}{item_zh}？"},
            {"kind": "need_to", "en": "{subject_cap} need to {verb} {item} before the deadline.", "zh": "{subject_zh}需要在截止前{verb_zh}{item_zh}。"},
            {"kind": "please_make_sure", "en": "Please make sure to {verb} {item} {adverb}.", "zh": "請務必{adverb_zh}{verb_zh}{item_zh}。"},
            {"kind": "if_clause", "en": "If necessary, {subject} can {verb} {item} right away.", "zh": "如果有需要，{subject_zh}可以立刻{verb_zh}{item_zh}。"},
            {"kind": "would_rather", "en": "{subject_cap} would rather {verb} {item} as soon as possible.", "zh": "{subject_zh}寧可儘快{verb_zh}{item_zh}。"},
        ],
        "modals": [("Would", "儘快", "as soon as possible")],
        "adverbs": [("carefully", "審慎地")],
        "time_phrases": [("before the deadline", "截止前")],
    },
}


QUESTION_TOPICS: List[Dict[str, Any]] = [
    {
        "key": "travel",
        "labels": ["travel", "trip", "airport", "hotel", "旅遊"],
        "subject": "I",
        "verb": {"beginner": "book", "intermediate": "reserve", "advanced": "arrange"},
        "verb_zh": "預訂",
        "items": [{"en": "a room", "zh": "房間"}, {"en": "a shuttle", "zh": "接駁車"}, {"en": "a train ticket", "zh": "火車票"}],
        "places": [{"en": "at the hotel", "zh": "在飯店"}, {"en": "at the station", "zh": "在車站"}, {"en": "for the trip", "zh": "為了旅程"}],
        "reasons": [("the schedule changed", "行程改了"), ("the flight is early", "班機很早"), ("the room is limited", "房間數量有限")],
    },
    {
        "key": "meeting",
        "labels": ["meeting", "work", "office", "briefing", "會議", "工作"],
        "subject": "we",
        "verb": {"beginner": "review", "intermediate": "discuss", "advanced": "go over"},
        "verb_zh": "檢視",
        "items": [{"en": "the agenda", "zh": "議程"}, {"en": "the action list", "zh": "行動清單"}, {"en": "the main points", "zh": "重點"}],
        "places": [{"en": "in the meeting room", "zh": "在會議室"}, {"en": "with the team", "zh": "和團隊一起"}, {"en": "before the briefing", "zh": "在簡報前"}],
        "reasons": [("the client is waiting", "客戶正在等"), ("we need a decision", "我們需要做決定"), ("the topic is important", "這個主題很重要")],
    },
    {
        "key": "restaurant",
        "labels": ["restaurant", "food", "order", "餐廳", "點餐"],
        "subject": "I",
        "verb": {"beginner": "order", "intermediate": "choose", "advanced": "request"},
        "verb_zh": "點",
        "items": [{"en": "a chicken sandwich", "zh": "雞肉三明治"}, {"en": "a bowl of soup", "zh": "一碗湯"}, {"en": "a glass of water", "zh": "一杯水"}],
        "places": [{"en": "at the restaurant", "zh": "在餐廳"}, {"en": "for lunch", "zh": "當作午餐"}, {"en": "from the menu", "zh": "從菜單上"}],
        "reasons": [("I am hungry", "我很餓"), ("the line is long", "排隊很長"), ("the special looks good", "今日特餐看起來不錯")],
    },
    {
        "key": "self_intro",
        "labels": ["self", "intro", "introduction", "自我介紹"],
        "subject": "I",
        "verb": {"beginner": "support", "intermediate": "assist", "advanced": "coordinate"},
        "verb_zh": "支援",
        "items": [{"en": "users", "zh": "使用者"}, {"en": "new staff", "zh": "新進同仁"}, {"en": "the help desk", "zh": "服務台"}],
        "places": [{"en": "in the IT department", "zh": "在資訊部門"}, {"en": "at work", "zh": "在工作上"}, {"en": "during office hours", "zh": "在上班時間"}],
        "reasons": [("that is my job", "那是我的工作"), ("the team needs help", "團隊需要協助"), ("service quality matters", "服務品質很重要")],
    },
    {
        "key": "phone",
        "labels": ["phone", "call", "telephone", "電話"],
        "subject": "I",
        "verb": {"beginner": "answer", "intermediate": "return", "advanced": "handle"},
        "verb_zh": "處理",
        "items": [{"en": "the call", "zh": "來電"}, {"en": "the message", "zh": "留言"}, {"en": "the voicemail", "zh": "語音訊息"}],
        "places": [{"en": "from my desk", "zh": "在我的座位"}, {"en": "before lunch", "zh": "在午餐前"}, {"en": "after the meeting", "zh": "在會後"}],
        "reasons": [("the client called again", "客戶又打來了"), ("it sounds urgent", "聽起來很急"), ("the manager asked me to", "主管請我處理")],
    },
    {
        "key": "shopping",
        "labels": ["shopping", "store", "mall", "購物", "買東西"],
        "subject": "I",
        "verb": {"beginner": "buy", "intermediate": "compare", "advanced": "choose"},
        "verb_zh": "選購",
        "items_by_level": {
            "beginner": [{"en": "a jacket", "zh": "外套"}, {"en": "a T-shirt", "zh": "T 恤"}, {"en": "a bag", "zh": "包包"}],
            "intermediate": [{"en": "the prices", "zh": "價格"}, {"en": "the sizes", "zh": "尺寸"}, {"en": "the colors", "zh": "顏色"}],
            "advanced": [{"en": "the best option", "zh": "最適合的選項"}, {"en": "the final item", "zh": "最後要買的商品"}, {"en": "the right size", "zh": "合適的尺寸"}],
        },
        "items": [{"en": "a jacket", "zh": "外套"}],
        "places": [{"en": "at the store", "zh": "在商店"}, {"en": "before checkout", "zh": "在結帳前"}, {"en": "at the mall", "zh": "在購物中心"}],
        "reasons": [("I need it today", "我今天需要"), ("the discount looks good", "折扣看起來不錯"), ("I want the best option", "我想選最好的選項")],
    },
    {
        "key": "hospital",
        "labels": ["hospital", "clinic", "doctor", "醫院", "看病"],
        "subject": "I",
        "verb": {"beginner": "see", "intermediate": "schedule", "advanced": "confirm"},
        "verb_zh": "安排",
        "items_by_level": {
            "beginner": [{"en": "a doctor", "zh": "醫生"}, {"en": "the doctor", "zh": "醫生"}, {"en": "a nurse", "zh": "護理師"}],
            "intermediate": [{"en": "an appointment", "zh": "預約"}, {"en": "a follow-up visit", "zh": "回診"}, {"en": "the appointment time", "zh": "預約時間"}],
            "advanced": [{"en": "the appointment details", "zh": "預約細節"}, {"en": "the consultation time", "zh": "看診時間"}, {"en": "the follow-up schedule", "zh": "後續門診安排"}],
        },
        "items": [{"en": "an appointment", "zh": "預約"}],
        "places": [{"en": "at the clinic", "zh": "在診所"}, {"en": "this afternoon", "zh": "今天下午"}, {"en": "before the visit", "zh": "在看診前"}],
        "reasons": [("I do not feel well", "我不太舒服"), ("the symptoms got worse", "症狀變嚴重了"), ("the doctor needs more details", "醫生需要更多資訊")],
    },
    {
        "key": "school",
        "labels": ["school", "class", "teacher", "學校", "上課"],
        "subject": "we",
        "verb": {"beginner": "finish", "intermediate": "complete", "advanced": "prepare"},
        "verb_zh": "完成",
        "items": [{"en": "the homework", "zh": "作業"}, {"en": "the worksheet", "zh": "學習單"}, {"en": "the presentation", "zh": "簡報"}],
        "places": [{"en": "in class", "zh": "在課堂上"}, {"en": "before school ends", "zh": "在放學前"}, {"en": "with our teacher", "zh": "和老師一起"}],
        "reasons": [("the teacher asked us to", "老師要求我們"), ("the deadline is near", "期限快到了"), ("the project is important", "這個專題很重要")],
    },
    {
        "key": "bank",
        "labels": ["bank", "atm", "account", "銀行"],
        "subject": "I",
        "verb": {"beginner": "check", "intermediate": "review", "advanced": "confirm"},
        "verb_zh": "確認",
        "items": [{"en": "my account", "zh": "我的帳戶"}, {"en": "the balance", "zh": "餘額"}, {"en": "the transfer record", "zh": "轉帳紀錄"}],
        "places": [{"en": "at the bank", "zh": "在銀行"}, {"en": "on the app", "zh": "在 App 上"}, {"en": "before the transfer", "zh": "在轉帳前"}],
        "reasons": [("I need the details", "我需要明細"), ("the amount looks unusual", "金額看起來不太對"), ("the bank asked me to", "銀行要求我確認")],
    },
    {
        "key": "delivery",
        "labels": ["delivery", "package", "shipping", "宅配", "物流"],
        "subject": "I",
        "verb": {"beginner": "track", "intermediate": "check", "advanced": "monitor"},
        "verb_zh": "追蹤",
        "items": [{"en": "the package", "zh": "包裹"}, {"en": "the shipment", "zh": "貨件"}, {"en": "the delivery status", "zh": "配送狀態"}],
        "places": [{"en": "online", "zh": "在線上"}, {"en": "before it arrives", "zh": "在送達前"}, {"en": "from my phone", "zh": "用手機"}],
        "reasons": [("it is arriving today", "它今天會到"), ("the customer is waiting", "客戶正在等"), ("the schedule changed", "配送時間改了")],
    },
    {
        "key": "weather",
        "labels": ["weather", "rain", "forecast", "天氣"],
        "subject": "we",
        "verb": {"beginner": "check", "intermediate": "review", "advanced": "monitor"},
        "verb_zh": "查看",
        "items": [{"en": "the forecast", "zh": "天氣預報"}, {"en": "the rain chance", "zh": "降雨機率"}, {"en": "the temperature", "zh": "氣溫"}],
        "places": [{"en": "before the trip", "zh": "在出發前"}, {"en": "every morning", "zh": "每天早上"}, {"en": "on the weather app", "zh": "在天氣 App 上"}],
        "reasons": [("we will go out", "我們要外出"), ("the sky looks dark", "天色看起來很暗"), ("the plan depends on it", "行程要看天氣")],
    },
    {
        "key": "fitness",
        "labels": ["fitness", "gym", "exercise", "健身", "運動"],
        "subject": "I",
        "verb": {"beginner": "do", "intermediate": "finish", "advanced": "complete"},
        "verb_zh": "完成",
        "items": [{"en": "my workout", "zh": "我的訓練"}, {"en": "the cardio session", "zh": "有氧訓練"}, {"en": "the warm-up", "zh": "暖身"}],
        "places": [{"en": "at the gym", "zh": "在健身房"}, {"en": "before dinner", "zh": "在晚餐前"}, {"en": "with my coach", "zh": "和教練一起"}],
        "reasons": [("I want to stay healthy", "我想保持健康"), ("the program requires it", "課表需要這樣做"), ("my coach suggested it", "教練建議我這樣做")],
    },
    {
        "key": "computer",
        "labels": ["computer", "software", "system", "電腦", "軟體"],
        "subject": "I",
        "verb": {"beginner": "update", "intermediate": "upgrade", "advanced": "configure"},
        "verb_zh": "設定",
        "items": [{"en": "the system", "zh": "系統"}, {"en": "the software", "zh": "軟體"}, {"en": "the settings", "zh": "設定"}],
        "places": [{"en": "on my computer", "zh": "在我的電腦上"}, {"en": "before restarting", "zh": "在重新開機前"}, {"en": "after work", "zh": "下班後"}],
        "reasons": [("the version is old", "版本太舊了"), ("the app is unstable", "程式不太穩定"), ("security matters", "安全性很重要")],
    },
    {
        "key": "customer_service",
        "labels": ["customer service", "support", "complaint", "客服"],
        "subject": "we",
        "verb": {"beginner": "help", "intermediate": "solve", "advanced": "resolve"},
        "verb_zh": "協助",
        "items_by_level": {
            "beginner": [{"en": "the customer", "zh": "客戶"}, {"en": "the caller", "zh": "來電者"}, {"en": "the visitor", "zh": "來訪者"}],
            "intermediate": [{"en": "the problem", "zh": "問題"}, {"en": "the complaint", "zh": "客訴"}, {"en": "the request", "zh": "需求"}],
            "advanced": [{"en": "the service issue", "zh": "服務問題"}, {"en": "the complaint case", "zh": "客訴案件"}, {"en": "the pending request", "zh": "待處理需求"}],
        },
        "items": [{"en": "the customer", "zh": "客戶"}],
        "places": [{"en": "at the service desk", "zh": "在服務櫃台"}, {"en": "through email", "zh": "透過電子郵件"}, {"en": "before the deadline", "zh": "在期限前"}],
        "reasons": [("the customer is upset", "客戶有點生氣"), ("the issue is urgent", "這個問題很急"), ("service quality matters", "服務品質很重要")],
    },
    {
        "key": "airport",
        "labels": ["airport", "boarding", "flight", "機場"],
        "subject": "I",
        "verb": {"beginner": "check", "intermediate": "confirm", "advanced": "verify"},
        "verb_zh": "確認",
        "items": [{"en": "my gate", "zh": "我的登機門"}, {"en": "the boarding time", "zh": "登機時間"}, {"en": "the flight status", "zh": "航班狀態"}],
        "places": [{"en": "at the airport", "zh": "在機場"}, {"en": "before security", "zh": "在安檢前"}, {"en": "on the display board", "zh": "在看板上"}],
        "reasons": [("the gate may change", "登機門可能會變"), ("the flight is delayed", "班機延誤了"), ("the announcement was unclear", "廣播不太清楚")],
    },
]
