from __future__ import annotations

from typing import Any, Dict, List


LEVEL_SETTINGS: Dict[str, Dict[str, Any]] = {
    "beginner": {
        "zh_label": "初級",
        "patterns": [
            {"en": "{subject_cap} usually {verb} {item} {place}.", "zh": "{subject_zh}通常會在{place_zh}{verb_zh}{item_zh}。"},
            {"en": "{subject_cap} can {verb} {item} {time_phrase}.", "zh": "{subject_zh}可以在{time_phrase_zh}{verb_zh}{item_zh}。"},
            {"en": "Please {verb} {item} {adverb}.", "zh": "請{adverb_zh}{verb_zh}{item_zh}。"},
        ],
        "adverbs": [("carefully", "小心地")],
        "time_phrases": [("this morning", "今天早上")],
    },
    "intermediate": {
        "zh_label": "中級",
        "patterns": [
            {"en": "{subject_cap} would like to {verb} {item} {place}.", "zh": "{subject_zh}想要在{place_zh}{verb_zh}{item_zh}。"},
            {"en": "{subject_cap} often {verb} {item} because {reason}.", "zh": "{subject_zh}常常{verb_zh}{item_zh}，因為{reason_zh}。"},
            {"en": "Could you {verb} {item} {adverb}?", "zh": "你可以{adverb_zh}{verb_zh}{item_zh}嗎？"},
        ],
        "adverbs": [("efficiently", "有效率地")],
        "time_phrases": [("before lunch", "午餐前")],
    },
    "advanced": {
        "zh_label": "高級",
        "patterns": [
            {"en": "{subject_cap} would rather {verb} {item} as soon as possible.", "zh": "{subject_zh}比較傾向盡快{verb_zh}{item_zh}。"},
            {"en": "Would it be possible to {verb} {item} {time_phrase}?", "zh": "是否可以在{time_phrase_zh}{verb_zh}{item_zh}？"},
            {"en": "Please make sure to {verb} {item} {adverb}.", "zh": "請務必{adverb_zh}{verb_zh}{item_zh}。"},
        ],
        "adverbs": [("carefully", "仔細地")],
        "time_phrases": [("before the deadline", "截止前")],
    },
}


QUESTION_TOPICS: List[Dict[str, Any]] = [
    {
        "key": "travel",
        "labels": ["travel", "trip", "airport", "hotel", "旅遊"],
        "subject": "I",
        "subject_zh": "我",
        "verb": {"beginner": "book", "intermediate": "reserve", "advanced": "arrange"},
        "verb_zh": "預訂",
        "items": [{"en": "a room", "zh": "房間"}, {"en": "a shuttle", "zh": "接駁車"}, {"en": "a ticket", "zh": "票"}],
        "places": [{"en": "at the hotel", "zh": "在飯店"}, {"en": "for the trip", "zh": "為了這趟旅程"}, {"en": "at the station", "zh": "在車站"}],
        "reasons": [("the schedule changed", "行程改了"), ("the flight is early", "班機很早"), ("the room is limited", "房間有限")],
    },
    {
        "key": "meeting",
        "labels": ["meeting", "office", "team", "work", "會議"],
        "subject": "we",
        "subject_zh": "我們",
        "verb": {"beginner": "review", "intermediate": "discuss", "advanced": "go over"},
        "verb_zh": "討論",
        "items": [{"en": "the agenda", "zh": "議程"}, {"en": "the action list", "zh": "行動清單"}, {"en": "the main points", "zh": "重點"}],
        "places": [{"en": "in the meeting room", "zh": "在會議室"}, {"en": "with the team", "zh": "和團隊一起"}, {"en": "before the briefing", "zh": "在簡報前"}],
        "reasons": [("the client is waiting", "客戶在等"), ("we need a decision", "我們需要決定"), ("the topic is important", "這個主題很重要")],
    },
    {
        "key": "restaurant",
        "labels": ["restaurant", "food", "order", "dining", "餐廳"],
        "subject": "I",
        "subject_zh": "我",
        "verb": {"beginner": "order", "intermediate": "choose", "advanced": "request"},
        "verb_zh": "點",
        "items": [{"en": "a chicken sandwich", "zh": "雞肉三明治"}, {"en": "a bowl of soup", "zh": "一碗湯"}, {"en": "a glass of water", "zh": "一杯水"}],
        "places": [{"en": "at the restaurant", "zh": "在餐廳"}, {"en": "for lunch", "zh": "當午餐"}, {"en": "from the menu", "zh": "從菜單上"}],
        "reasons": [("I am hungry", "我餓了"), ("the line is long", "排隊很長"), ("the special looks good", "今日特餐看起來不錯")],
    },
    {
        "key": "self_intro",
        "labels": ["self", "introduction", "intro", "自我介紹"],
        "subject": "I",
        "subject_zh": "我",
        "verb": {"beginner": "support", "intermediate": "assist", "advanced": "coordinate"},
        "verb_zh": "協助",
        "items": [{"en": "users", "zh": "使用者"}, {"en": "new staff", "zh": "新同事"}, {"en": "the help desk", "zh": "服務台"}],
        "places": [{"en": "in the IT department", "zh": "在資訊部門"}, {"en": "at work", "zh": "在工作上"}, {"en": "during office hours", "zh": "在上班時間"}],
        "reasons": [("that is my job", "那是我的工作"), ("the team needs help", "團隊需要幫助"), ("service quality matters", "服務品質很重要")],
    },
    {
        "key": "phone",
        "labels": ["phone", "call", "telephone", "電話"],
        "subject": "I",
        "subject_zh": "我",
        "verb": {"beginner": "answer", "intermediate": "return", "advanced": "handle"},
        "verb_zh": "處理",
        "items": [{"en": "the call", "zh": "電話"}, {"en": "the message", "zh": "訊息"}, {"en": "the voicemail", "zh": "語音留言"}],
        "places": [{"en": "from my desk", "zh": "在座位上"}, {"en": "before lunch", "zh": "午餐前"}, {"en": "after the meeting", "zh": "會後"}],
        "reasons": [("the client called again", "客戶又打來了"), ("it sounds urgent", "聽起來很急"), ("the manager asked me to", "主管要我這麼做")],
    },
    {
        "key": "shopping",
        "labels": ["shopping", "store", "mall", "買東西", "購物"],
        "subject": "I",
        "subject_zh": "我",
        "verb": {"beginner": "buy", "intermediate": "compare", "advanced": "choose"},
        "verb_zh": "挑選",
        "items_by_level": {
            "beginner": [{"en": "a jacket", "zh": "外套"}, {"en": "a T-shirt", "zh": "T 恤"}, {"en": "a bag", "zh": "包包"}],
            "intermediate": [{"en": "the prices", "zh": "價格"}, {"en": "the sizes", "zh": "尺寸"}, {"en": "the colors", "zh": "顏色"}],
            "advanced": [{"en": "the best option", "zh": "最佳選項"}, {"en": "the final item", "zh": "最後要買的東西"}, {"en": "the right size", "zh": "合適尺寸"}],
        },
        "items": [{"en": "a jacket", "zh": "外套"}],
        "places": [{"en": "at the store", "zh": "在店裡"}, {"en": "before checkout", "zh": "結帳前"}, {"en": "at the mall", "zh": "在百貨公司"}],
        "reasons": [("I need it today", "我今天就要"), ("the discount looks good", "折扣不錯"), ("I want the best option", "我想選最好的")],
    },
    {
        "key": "hospital",
        "labels": ["hospital", "clinic", "doctor", "醫院"],
        "subject": "I",
        "subject_zh": "我",
        "verb": {"beginner": "see", "intermediate": "schedule", "advanced": "confirm"},
        "verb_zh": "安排",
        "items_by_level": {
            "beginner": [{"en": "a doctor", "zh": "醫生"}, {"en": "the doctor", "zh": "那位醫生"}, {"en": "a nurse", "zh": "護理師"}],
            "intermediate": [{"en": "an appointment", "zh": "預約"}, {"en": "a follow-up visit", "zh": "回診"}, {"en": "the appointment time", "zh": "預約時間"}],
            "advanced": [{"en": "the appointment details", "zh": "預約細節"}, {"en": "the consultation time", "zh": "看診時間"}, {"en": "the follow-up schedule", "zh": "回診安排"}],
        },
        "items": [{"en": "an appointment", "zh": "預約"}],
        "places": [{"en": "at the clinic", "zh": "在診所"}, {"en": "this afternoon", "zh": "今天下午"}, {"en": "before the visit", "zh": "看診前"}],
        "reasons": [("I do not feel well", "我不太舒服"), ("the symptoms got worse", "症狀變嚴重了"), ("the doctor needs more details", "醫生需要更多資訊")],
    },
    {
        "key": "school",
        "labels": ["school", "class", "teacher", "學校"],
        "subject": "we",
        "subject_zh": "我們",
        "verb": {"beginner": "finish", "intermediate": "complete", "advanced": "prepare"},
        "verb_zh": "完成",
        "items": [{"en": "the homework", "zh": "作業"}, {"en": "the worksheet", "zh": "學習單"}, {"en": "the presentation", "zh": "簡報"}],
        "places": [{"en": "in class", "zh": "在課堂上"}, {"en": "before school ends", "zh": "放學前"}, {"en": "with our teacher", "zh": "和老師一起"}],
        "reasons": [("the teacher asked us to", "老師要我們做"), ("the deadline is near", "期限快到了"), ("the project is important", "這個專題很重要")],
    },
    {
        "key": "weather",
        "labels": ["weather", "rain", "forecast", "天氣"],
        "subject": "we",
        "subject_zh": "我們",
        "verb": {"beginner": "check", "intermediate": "review", "advanced": "monitor"},
        "verb_zh": "查看",
        "items": [{"en": "the forecast", "zh": "天氣預報"}, {"en": "the rain chance", "zh": "降雨機率"}, {"en": "the temperature", "zh": "氣溫"}],
        "places": [{"en": "before the trip", "zh": "出發前"}, {"en": "every morning", "zh": "每天早上"}, {"en": "on the weather app", "zh": "在天氣 App 上"}],
        "reasons": [("we will go out", "我們要出門"), ("the sky looks dark", "天色很暗"), ("the plan depends on it", "行程要看天氣")],
    },
    {
        "key": "fitness",
        "labels": ["fitness", "gym", "exercise", "健身"],
        "subject": "I",
        "subject_zh": "我",
        "verb": {"beginner": "do", "intermediate": "finish", "advanced": "complete"},
        "verb_zh": "完成",
        "items": [{"en": "my workout", "zh": "我的訓練"}, {"en": "the cardio session", "zh": "有氧訓練"}, {"en": "the warm-up", "zh": "暖身"}],
        "places": [{"en": "at the gym", "zh": "在健身房"}, {"en": "before dinner", "zh": "晚餐前"}, {"en": "with my coach", "zh": "和教練一起"}],
        "reasons": [("I want to stay healthy", "我想維持健康"), ("the program requires it", "課表需要"), ("my coach suggested it", "教練建議我這樣做")],
    },
]
