# Generated by Django 6.0 on 2026-01-13 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ============================================================
        # Add new fields (scope/owner + new schema v2 columns)
        # ============================================================

        migrations.AddField(
            model_name="documenttemplate",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doc_templates",
                to=settings.AUTH_USER_MODEL,
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="scope",
            field=models.CharField(
                choices=[("public", "?祇?"), ("personal", "?犖")],
                db_index=True,
                default="public",
                max_length=20,
            ),
        ),

        # ???啣嚗?瑽?畾菔嚗敹?
        migrations.AddField(
            model_name="documenttemplate",
            name="sections",
            field=models.JSONField(blank=True, default=dict),
        ),

        # ???啣嚗?憭?雿??賜阮?嗡辣???啣?/?交?蝑?
        migrations.AddField(
            model_name="documenttemplate",
            name="doc_fields",
            field=models.JSONField(blank=True, default=dict),
        ),

        # ???啣嚗chema version + meta
        migrations.AddField(
            model_name="documenttemplate",
            name="schema_ver",
            field=models.PositiveSmallIntegerField(db_index=True, default=2),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),

        # ???舫嚗??摮??汗/?冽?瑼Ｙ揣/?臬嚗?
        migrations.AddField(
            model_name="documenttemplate",
            name="content_text",
            field=models.TextField(blank=True, default=""),
        ),

        # ??tags: list[str]

        # ============================================================
        # Alter existing fields (align model)
        # ============================================================

        migrations.AlterField(
            model_name="documenttemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="description",
            field=models.CharField(blank=True, default="", max_length=400),
        ),

        # ??doc_type ?唬誨蝣?+ max_length=40
        migrations.AlterField(
            model_name="documenttemplate",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("sign_memo", "蝪賢?"),
                    ("order_draft", "隞斤阮"),
                    ("submit_draft", "?阮"),
                    ("letter_draft", "?賜阮"),
                    ("note", "靘輻惜"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),

        # ============================================================
        # Indexes
        # ============================================================

        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["doc_type", "scope", "created_at"],
                name="idx_doc_type_scope_created",
            ),
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["schema_ver", "doc_type"],
                name="idx_doc_schema_doctype",
            ),
        ),

        # ============================================================
        # Constraints
        # ============================================================

        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                condition=Q(scope="public"),
                fields=("title",),
                name="uniq_doc_template_public_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                condition=Q(scope="personal") & Q(owner__isnull=False),
                fields=("owner", "title"),
                name="uniq_doc_template_personal_owner_title",
            ),
        ),
    ]
