# Generated by Django 6.0 on 2026-01-14

from django.db import migrations


def copy_content_to_content_text(apps, schema_editor):
    DocumentTemplate = apps.get_model("doc", "DocumentTemplate")
    for obj in DocumentTemplate.objects.all().only("id", "content", "content_text"):
        old = getattr(obj, "content", None)
        if old and not (obj.content_text or ""):
            obj.content_text = old
            obj.save(update_fields=["content_text"])


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0002_documenttemplate_owner_documenttemplate_scope_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_content_to_content_text, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="content",
        ),
    ]