# Generated by Django 6.0 on 2026-01-14

from django.db import migrations, models


def copy_content_to_content_text(apps, schema_editor):
    DocumentTemplate = apps.get_model("doc", "DocumentTemplate")

    # 把舊 content 搬到新 content_text（如果舊欄位存在且有值）
    for obj in DocumentTemplate.objects.all().only("id", "content", "content_text"):
        old = getattr(obj, "content", None)
        if old and not (obj.content_text or ""):
            obj.content_text = old
            obj.save(update_fields=["content_text"])


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0002_documenttemplate_owner_documenttemplate_scope_and_more"),
    ]

    operations = [
        # 1) 新增新 schema 欄位
        migrations.AddField(
            model_name="documenttemplate",
            name="sections",
            field=models.JSONField(default=dict, blank=True),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="doc_fields",
            field=models.JSONField(default=dict, blank=True),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="schema_ver",
            field=models.PositiveSmallIntegerField(default=2, db_index=True),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="meta",
            field=models.JSONField(default=dict, blank=True),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="content_text",
            field=models.TextField(blank=True, default=""),
        ),

        # 2) 搬資料：content -> content_text
        migrations.RunPython(copy_content_to_content_text, migrations.RunPython.noop),

        # 3) 移除舊 content 欄位（解掉 NOT NULL constraint 問題）
        migrations.RemoveField(
            model_name="documenttemplate",
            name="content",
        ),
    ]
