# Generated by Django 6.0 on 2026-01-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_documenttemplate_schema_v2'),
    ]

    operations = [
    ]
