# Generated by Django 6.0 on 2026-05-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_auto_20260114_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='doc_type',
            field=models.CharField(choices=[('sign_memo', '簽呈'), ('order_draft', '令稿'), ('submit_draft', '呈稿'), ('letter_draft', '函稿'), ('note', '便籤')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='scope',
            field=models.CharField(choices=[('public', '公開'), ('personal', '個人')], db_index=True, default='public', max_length=20),
        ),
    ]
