# Generated by Django 6.0 on 2026-08-29 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WrentRentalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_pickup_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='實際取車時間')),
                ('actual_return_time', models.DateTimeField(blank=True, null=True, verbose_name='實際還車時間')),
                ('pickup_mileage', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='取車里程 (km)')),
                ('return_mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='還車里程 (km)')),
                ('pickup_fuel', models.PositiveIntegerField(default=100, verbose_name='取車油/電量 (%)')),
                ('return_fuel', models.PositiveIntegerField(blank=True, null=True, verbose_name='還車油/電量 (%)')),
                ('checkout_notes', models.TextField(blank=True, default='', verbose_name='取車車況記錄與備註')),
                ('checkin_notes', models.TextField(blank=True, default='', verbose_name='還車車況驗收備註')),
                ('status', models.CharField(choices=[('IN_PROGRESS', '行程進行中 (IN_PROGRESS)'), ('RETURNED', '已驗車還車 (RETURNED)')], default='IN_PROGRESS', max_length=20, verbose_name='租賃狀態')),
            ],
            options={
                'verbose_name': '實際租賃記錄',
                'verbose_name_plural': '實際租賃記錄列表',
                'db_table': 'wrent_rental_record',
            },
        ),
        migrations.CreateModel(
            name='WrentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_no', models.CharField(max_length=50, unique=True, verbose_name='預約單號')),
                ('user_name', models.CharField(max_length=100, verbose_name='預約人姓名/帳號')),
                ('user_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='預約人電話')),
                ('start_time', models.DateTimeField(verbose_name='預約取車時間')),
                ('end_time', models.DateTimeField(verbose_name='預約還車時間')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='預估租金 (元)')),
                ('has_insurance', models.BooleanField(default=False, verbose_name='加購安心保險')),
                ('status', models.CharField(choices=[('CONFIRMED', '已確認 (CONFIRMED)'), ('PICKED_UP', '已取車 (PICKED_UP)'), ('COMPLETED', '已還車結算 (COMPLETED)'), ('CANCELLED', '已取消 (CANCELLED)'), ('NO_SHOW', '逾時未取 (NO_SHOW)')], default='CONFIRMED', max_length=20, verbose_name='預約狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='預約建立時間')),
            ],
            options={
                'verbose_name': '租車預約單',
                'verbose_name_plural': '租車預約單列表',
                'db_table': 'wrent_reservation',
            },
        ),
        migrations.CreateModel(
            name='WrentStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=30, unique=True, verbose_name='站點代碼')),
                ('name', models.CharField(max_length=100, verbose_name='站點名稱')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('capacity', models.PositiveIntegerField(default=10, verbose_name='車位容量')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='聯絡電話')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否營運中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '租賃站點',
                'verbose_name_plural': '租賃站點列表',
                'db_table': 'wrent_station',
            },
        ),
        migrations.CreateModel(
            name='WrentVehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=30, unique=True, verbose_name='車型代碼')),
                ('name', models.CharField(max_length=100, verbose_name='車型名稱')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=120.0, max_digits=10, verbose_name='時租費率 (元/小時)')),
                ('daily_cap_rate', models.DecimalField(decimal_places=2, default=1200.0, max_digits=10, verbose_name='單日封頂費率 (元/日)')),
                ('mileage_rate', models.DecimalField(decimal_places=2, default=3.2, max_digits=10, verbose_name='里程費率 (元/公里)')),
                ('overdue_hourly_rate', models.DecimalField(decimal_places=2, default=180.0, max_digits=10, verbose_name='逾期加成費率 (元/小時)')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='押金金額 (元)')),
                ('description', models.TextField(blank=True, default='', verbose_name='車型說明')),
            ],
            options={
                'verbose_name': '車型等級費率',
                'verbose_name_plural': '車型等級費率列表',
                'db_table': 'wrent_vehicle_category',
            },
        ),
        migrations.CreateModel(
            name='WrentBillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True, verbose_name='帳單號碼')),
                ('total_hours_billed', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='計費時長 (小時)')),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='行駛里程 (公里)')),
                ('base_time_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='基礎時間租金 (元)')),
                ('mileage_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='里程耗能費用 (元)')),
                ('overdue_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='逾時還車罰則 (元)')),
                ('cross_station_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='跨站調度費 (元)')),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='保險費 (元)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='折抵優惠金額 (元)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='應付總金額 (元)')),
                ('payment_status', models.CharField(choices=[('UNPAID', '待扣款/待繳費'), ('PAID', '已扣款完成'), ('REFUNDED', '已退款')], default='PAID', max_length=20, verbose_name='扣款狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='出帳時間')),
                ('rental_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='wrent.wrentrentalrecord', verbose_name='關聯租借單')),
            ],
            options={
                'verbose_name': '租車結算帳單',
                'verbose_name_plural': '租車結算帳單列表',
                'db_table': 'wrent_billing_invoice',
            },
        ),
        migrations.AddField(
            model_name='wrentrentalrecord',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_record', to='wrent.wrentreservation', verbose_name='關聯預約'),
        ),
        migrations.AddField(
            model_name='wrentreservation',
            name='pickup_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_reservations', to='wrent.wrentstation', verbose_name='預計取車站點'),
        ),
        migrations.AddField(
            model_name='wrentreservation',
            name='return_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_reservations', to='wrent.wrentstation', verbose_name='預計還車站點'),
        ),
        migrations.CreateModel(
            name='WrentVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='車牌號碼')),
                ('model_name', models.CharField(default='Toyota Vios', max_length=100, verbose_name='車輛廠牌型號')),
                ('status', models.CharField(choices=[('AVAILABLE', '可租借 (AVAILABLE)'), ('RESERVED', '已預約 (RESERVED)'), ('RENTED', '租賃中 (RENTED)'), ('CLEANING', '整備清潔中 (CLEANING)'), ('MAINTENANCE', '保養維修中 (MAINTENANCE)')], default='AVAILABLE', max_length=20, verbose_name='車況狀態')),
                ('current_mileage', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12, verbose_name='目前總里程 (km)')),
                ('fuel_or_battery_level', models.PositiveIntegerField(default=100, verbose_name='剩餘油/電量百分比 (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上線運作')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('current_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='wrent.wrentstation', verbose_name='所在站點')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='wrent.wrentvehiclecategory', verbose_name='所屬車型')),
            ],
            options={
                'verbose_name': '租賃車輛實體',
                'verbose_name_plural': '租賃車輛實體列表',
                'db_table': 'wrent_vehicle',
            },
        ),
        migrations.AddField(
            model_name='wrentreservation',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrent.wrentvehicle', verbose_name='指定/配賦車輛'),
        ),
        migrations.AddField(
            model_name='wrentrentalrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_records', to='wrent.wrentvehicle', verbose_name='租借車輛'),
        ),
        migrations.AddField(
            model_name='wrentreservation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wrent.wrentvehiclecategory', verbose_name='預約車型'),
        ),
    ]
