"""
Django settings for webproj project.
Generated by 'django-admin startproject' using Django 6.0.
"""

from __future__ import annotations

from pathlib import Path
import os
import re
import sys
from dotenv import load_dotenv

# Tesseract
os.environ.setdefault("TESSDATA_PREFIX", r"C:\Program Files\Tesseract-OCR")

# ============================================================
# Base
# ============================================================
BASE_DIR_RESOLVED = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR_RESOLVED / ".env")

def _load_db_factory_md_into_environ(base_dir: Path) -> None:
    """
    Allow DB-related settings to be moved from .env into .env_DB_factory.
    .env_DB_factory values override .env for supported keys.
    """
    custom = (os.getenv("DB_FACTORY_MD_PATH") or "").strip()
    p = Path(custom) if custom else (base_dir / ".env_DB_factory")
    if not p.exists():
        return
    try:
        text = p.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return

    def _ok_key(key: str) -> bool:
        k = (key or "").strip().upper()
        return (
            k.startswith("DOC_DB_")
            or k.startswith("ORA_")
            or k.startswith("SQL_SERVER_")
            or k.startswith("SYBASE_")
            or k == "TEXT_MAX_CHARS"
        )

    def _unquote(v: str) -> str:
        s = (v or "").strip()
        if len(s) >= 2 and ((s[0] == '"' and s[-1] == '"') or (s[0] == "'" and s[-1] == "'")):
            return s[1:-1]
        return s

    for raw in text.splitlines():
        line = (raw or "").strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$", line)
        if not m:
            continue
        key = (m.group(1) or "").strip().upper()
        if not _ok_key(key):
            continue
        os.environ[key] = _unquote(m.group(2) or "")


_load_db_factory_md_into_environ(BASE_DIR_RESOLVED)

# ============================================================
# ENV helpers
# ============================================================
def env_bool(name: str, default: bool = False) -> bool:
    v = (os.getenv(name) or "").strip().lower()
    if v == "":
        return default
    return v in ("1", "true", "yes", "y", "on")

ORACLE_ENABLED = env_bool("ORACLE_ENABLED", False)
ORACLE_EMP_ENABLED = env_bool("ORACLE_EMP_ENABLED", False)



def env_int(key: str, default: int) -> int:
    try:
        return int((os.getenv(key) or "").strip() or default)
    except Exception:
        return default


def env_str(key: str, default: str = "") -> str:
    """
    正確版：
    - 沒設（None） → 用 default
    - 有設但為空字串 → 視為「刻意設空」，不要回退 default
    """
    v = os.getenv(key)
    if v is None:
        v = default
    return (v or "").strip()


def env_list(key: str, default: str = "") -> list[str]:
    s = env_str(key, default)
    return [x.strip() for x in s.split(",") if x.strip()]

# ============================================================
# ENV name
# ============================================================

def _norm_prefix(p: str) -> str:
    """
    Normalize proxy prefix:
    - "" -> ""
    - "djangoai" -> "/djangoai"
    - "/djangoai/" -> "/djangoai"
    - "/" -> ""   (treat root as no prefix)
    """
    p = (p or "").strip()
    if not p:
        return ""
    if not p.startswith("/"):
        p = "/" + p
    if p == "/":
        return ""
    while len(p) > 1 and p.endswith("/"):
        p = p[:-1]
    return p


# ============================================================
# ✅ NO_PROXY（強制保護：避免 requests/httpx 走公司代理打內網爆炸）
# ============================================================
_DEFAULT_NO_PROXY = "127.0.0.1,localhost,::1,.mpc.mil.tw,mpcai.mpc.mil.tw"
_no_proxy_env = os.getenv("NO_PROXY")
if _no_proxy_env is None or not _no_proxy_env.strip():
    os.environ["NO_PROXY"] = _DEFAULT_NO_PROXY
    os.environ["no_proxy"] = _DEFAULT_NO_PROXY
else:
    os.environ["NO_PROXY"] = _no_proxy_env
    os.environ["no_proxy"] = _no_proxy_env


# ============================================================
# Security / Debug
# ============================================================
ENV_NAME = env_str("ENV", "EXT").strip().upper()

SECRET_KEY = env_str(
    "DJANGO_SECRET_KEY",
    "django-insecure-u2crmik5h*mugnf1a1)g**vip6&gvd_wjde4k6w2(iu+0z24&%",
)

# ✅ 資安加固：正式環境強制關閉 DEBUG
DEBUG = env_bool("DJANGO_DEBUG", default=False) if ENV_NAME in ("INT", "EXT", "PROD") else env_bool("DJANGO_DEBUG", default=True)
IS_RUNSERVER = any(str(arg).startswith("runserver") for arg in sys.argv[1:])

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "mpcai.mpc.mil.tw,10.29.136.17,127.0.0.1,localhost")

# ✅ 資安標頭加固
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", True)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", True)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# ============================================================
# ✅ 環境與磁碟路徑自動切換 (ENV=EXT: H磁碟, ENV=INT: D磁碟)
# ============================================================

# 根據環境決定基礎磁碟 (H:\AI\AI_TOOLS 或 D:\AI\AI_TOOLS)
_TARGET_DRIVE = "H:" if ENV_NAME == "EXT" else "D:"

# 獲取當前文件的絕對路徑
current_dir = os.path.dirname(os.path.abspath(__file__))

# 獲取專案根目錄的絕對路徑
_PROJECT_ROOT_STR = os.path.abspath(os.path.join(current_dir, '..'))
# 強制修正 BASE_DIR 以驅動器代號開始，避免 UNC 路徑導致 staticfiles.W004 警告
BASE_DIR = Path(_PROJECT_ROOT_STR)

# ============================================================
# ✅ Reverse proxy / IIS（全站統一：PROXY_PREFIX + FORCE_SCRIPT_NAME）
# ============================================================
# - PROXY_PREFIX：對外入口前綴（例如 /djangoai）
# - FORCE_SCRIPT_NAME：只影響 reverse() / {% url %}（專案規範：反代模式通常設空字串）
ENV_IS_PUBLIC = ENV_NAME in ("INT", "EXT", "PROD", "STAGE", "UAT")
_DEFAULT_PROXY_PREFIX = "/djangoai" if ENV_IS_PUBLIC else ""

_raw_proxy_prefix = os.getenv("PROXY_PREFIX")
if _raw_proxy_prefix is None:
    PROXY_PREFIX = _norm_prefix(_DEFAULT_PROXY_PREFIX)
else:
    PROXY_PREFIX = _norm_prefix(_raw_proxy_prefix)

_raw_force_script_name = os.getenv("FORCE_SCRIPT_NAME")
if _raw_force_script_name is None:
    FORCE_SCRIPT_NAME = _norm_prefix(PROXY_PREFIX)
else:
    FORCE_SCRIPT_NAME = _norm_prefix(_raw_force_script_name)

# ✅ reverse() / {% url %} 是否帶 prefix：只看 FORCE_SCRIPT_NAME

# 是否信任 X-Forwarded-Prefix header（預設不信任，避免被偽造）
TRUST_X_FORWARDED_PREFIX = env_bool("TRUST_X_FORWARDED_PREFIX", default=False)

# ✅ 讓 middleware_proxy_prefix 寫回 SCRIPT_NAME（讓 request.script_name 成為唯一真相）
PROXY_PREFIX_WRITE_SCRIPT_NAME = env_bool("PROXY_PREFIX_WRITE_SCRIPT_NAME", default=bool(PROXY_PREFIX))

# (可選) Debug log 開關
PROXY_PREFIX_DEBUG_LOG = env_bool("PROXY_PREFIX_DEBUG_LOG", default=False)

# IIS/ARR 常見：外部 https、內部 http
USE_X_FORWARDED_HOST = env_bool("USE_X_FORWARDED_HOST", default=True)
SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    env_str("SECURE_PROXY_SSL_VALUE", "https"),
)

# ============================================================
# CORS
# ============================================================
CORS_ALLOW_ALL_ORIGINS = True

# ============================================================
# ✅ MODEL_TYPE
# ============================================================
MODEL_TYPE = env_str("MODEL_TYPE", "OPENAI").upper()
MODEL_TIMEOUT = env_int("MODEL_TIMEOUT", 120)

# Enforce provider policy by environment.
# Keep os.environ in sync because llm_factory reads from environment variables.
if ENV_NAME == "INT":
    MODEL_TYPE = "LM_STUDIO"
    os.environ["MODEL_TYPE"] = MODEL_TYPE
    if not (os.getenv("LM_STUDIO_MODEL") or "").strip():
        os.environ["LM_STUDIO_MODEL"] = "gemma-4"
elif ENV_NAME == "EXT":
    MODEL_TYPE = "OPENAI"
    os.environ["MODEL_TYPE"] = MODEL_TYPE

# ============================================================
# OpenAI
# ============================================================
OPENAI_API_KEY = env_str("OPENAI_API_KEY", "")
OPENAI_MODEL = env_str("OPENAI_MODEL", "gpt-4o-mini")
OPENAI_BASE_URL = env_str("OPENAI_BASE_URL", "https://api.openai.com")
OPENAI_TIMEOUT = env_int("OPENAI_TIMEOUT", 60)

# ============================================================
# Ollama（保留）
# ============================================================
OLLAMA_BASE_URL = env_str("OLLAMA_BASE_URL", "")
OLLAMA_MODEL = env_str("OLLAMA_MODEL", "")

if not OLLAMA_BASE_URL:
    OLLAMA_BASE_URL = env_str("MODEL_BASE_URL", "http://mpcai.mpc.mil.tw:11434")
if not OLLAMA_MODEL:
    OLLAMA_MODEL = env_str("MODEL_NAME", "magistral-small")

MODEL_BASE_URL = OLLAMA_BASE_URL
MODEL_NAME = OLLAMA_MODEL

MODEL_APR_KEY = env_str("MODEL_APR_KEY", "")
MODEL_API_KEY = env_str("MODEL_API_KEY", MODEL_APR_KEY)

USE_OLLAMA_FIRST = env_bool("USE_OLLAMA_FIRST", default=True)
OLLAMA_BASE_URL_EXTERNAL = env_str("OLLAMA_BASE_URL_EXTERNAL", "")
OLLAMA_MODE = env_str("OLLAMA_MODE", "CHAT").upper()
OLLAMA_EMBED_MODEL = env_str("OLLAMA_EMBED_MODEL", "nomic-embed-text")

# ============================================================
# Video tools
# ============================================================
YTDLP_BIN = env_str("YTDLP_BIN", "yt-dlp")
FFMPEG_BIN = env_str("FFMPEG_BIN", "ffmpeg")

# ============================================================
# LangChain（保留原樣）
# ============================================================
LANGCHAIN = {
    "MODEL": "ollama",
    "Ollama": {
        "model": env_str("LANGCHAIN_OLLAMA_MODEL", "mistral_small_3_1_2503:latest"),
        "temperature": float(env_str("LANGCHAIN_TEMPERATURE", "0.7") or "0.7"),
    },
}

# ============================================================
# Portal ACL（保留原樣）
# ============================================================
PORTAL_ACL_ENABLED = env_bool("PORTAL_ACL_ENABLED", default=False)
PORTAL_ACL_BACKEND = env_str("PORTAL_ACL_BACKEND", "AUTO").upper()


def _resolve_acl_backend(model_type: str, backend: str) -> str:
    if backend == "AUTO":
        return "ORACLE" if model_type == "OLLAMA" else "DJANGO"
    if backend in ("ORACLE", "DJANGO"):
        return backend
    return "DJANGO"


ACL_BACKEND_EFFECTIVE = _resolve_acl_backend(MODEL_TYPE, PORTAL_ACL_BACKEND)

PORTAL_ACL = {
    "portal": ["網頁系統管理員"],
    "student": ["PUBLIC"],
    "translator": ["ALL_AUTHENTICATED"],
    "englishchat": ["ALL_AUTHENTICATED"],
    "chatbotui": ["ALL_AUTHENTICATED"],
    "todo": ["ALL_AUTHENTICATED"],
    "comment": [
        "ALL_AUTHENTICATED",
        "人事資訊管理",
        "服務中心人員群組",
        "中心雲端網頁通用群組",
    ],
    "doc": [
        "ALL_AUTHENTICATED",
         "服務中心人員群組",
    ],
    "meetingreply": [
        "ALL_AUTHENTICATED",
        "MEETING",
        "會議管制系統",
    ],
    "graph": [
        "ALL_AUTHENTICATED",
        "GRAPH",
        "服務中心人員群組",
    ],
    "pdf": ["ALL_AUTHENTICATED"],
    "pptx": ["ALL_AUTHENTICATED"],
    "tts": ["ALL_AUTHENTICATED"],
    "rag": ["ALL_AUTHENTICATED"],
    "digital_twin_kb": ["ALL_AUTHENTICATED"],
    "vanna": [
        "DB",
        "中心雲端系統跨廠權限",
        "服務中心人員群組",
    ],
    "excelproc": ["計資組業管資料管理"],
    "usage": ["網頁系統管理員"],
    "projectnotes": ["ALL_AUTHENTICATED"],
    "formalize": ["ALL_AUTHENTICATED"],
    "videolearning": ["ALL_AUTHENTICATED"],
    "open_notebook": ["ALL_AUTHENTICATED"],
}

# ============================================================
# Oracle / SQL Server / Sybase / RAG ...（保留）
# ============================================================
ORA_HOST = env_str("ORA_HOST", "")
ORA_PORT = env_int("ORA_PORT", 1521)
ORA_SERVICE_NAME = env_str("ORA_SERVICE_NAME", "")
ORA_USER = env_str("ORA_USER", "")
ORA_PASS = env_str("ORA_PASS", "")
ORA_ACL_TABLE = env_str("ORA_ACL_TABLE", "VIEW_ZZ_USER_GROUP_ACL")
ORA_ACL_USER_COL = env_str("ORA_ACL_USER_COL", "USERNAME")
ORA_ACL_GROUP_COL = env_str("ORA_ACL_GROUP_COL", "GROUP_NAME")

SQL_SERVER_HOST = env_str("SQL_SERVER_HOST", "")
SQL_SERVER_PORT = env_str("SQL_SERVER_PORT", "1433")
SQL_SERVER_DB = env_str("SQL_SERVER_DB", "CaseManager")
SQL_SERVER_USER = env_str("SQL_SERVER_USER", "")
SQL_SERVER_PASS = env_str("SQL_SERVER_PASS", "")
SQL_SERVER_DRIVER = env_str("SQL_SERVER_DRIVER", "ODBC Driver 17 for SQL Server")
SQL_SERVER_RAG_VIEW = env_str("SQL_SERVER_RAG_VIEW", "dbo.view_rag_cm_qna")
SQL_SERVER_FETCH_SIZE = env_int("SQL_SERVER_FETCH_SIZE", 200)
SQL_SERVER_UPSERT_BATCH = env_int("SQL_SERVER_UPSERT_BATCH", 200)

# ============================================================
# Digital Twin Knowledge Base
# - Integrated app under webapps.digital_twin_kb.
# - Uses root .env and root requirements.txt; no standalone project config.
# ============================================================
DIGITAL_TWIN_KB_DOCS_DIR = Path(
    env_str("DIGITAL_TWIN_KB_DOCS_DIR", str(BASE_DIR / "documents" / "digital_twin_kb"))
)
DIGITAL_TWIN_KB_STORAGE_DIR = Path(
    env_str("DIGITAL_TWIN_KB_STORAGE_DIR", str(BASE_DIR / "media" / "digital_twin_kb"))
)
DIGITAL_TWIN_KB_EMBEDDING_MODEL = env_str(
    "DIGITAL_TWIN_KB_EMBEDDING_MODEL",
    "sentence-transformers/all-MiniLM-L6-v2",
)
DIGITAL_TWIN_KB_EMBEDDING_DIMENSIONS = env_int("DIGITAL_TWIN_KB_EMBEDDING_DIMENSIONS", 384)
DIGITAL_TWIN_KB_ENABLE_EMBEDDING = env_bool("DIGITAL_TWIN_KB_ENABLE_EMBEDDING", True)
DIGITAL_TWIN_KB_TOP_K = env_int("DIGITAL_TWIN_KB_TOP_K", 5)
DIGITAL_TWIN_KB_LLM_PROVIDER = env_str("DIGITAL_TWIN_KB_LLM_PROVIDER", "")
DIGITAL_TWIN_KB_OPENAI_MODEL = env_str("DIGITAL_TWIN_KB_OPENAI_MODEL", "")
if ENV_NAME == "INT" and not DIGITAL_TWIN_KB_LLM_PROVIDER:
    DIGITAL_TWIN_KB_LLM_PROVIDER = "LM_STUDIO"
elif ENV_NAME == "EXT" and not DIGITAL_TWIN_KB_LLM_PROVIDER:
    DIGITAL_TWIN_KB_LLM_PROVIDER = "OPENAI"

SYBASE_DSN = env_str("SYBASE_DSN", "")
SYBASE_HOST = env_str("SYBASE_HOST", "")
SYBASE_PORT = env_int("SYBASE_PORT", 5000)
SYBASE_DB = env_str("SYBASE_DB", "")
SYBASE_USER = env_str("SYBASE_USER", "")
SYBASE_PASS = env_str("SYBASE_PASS", "")
SYBASE_DRIVER = env_str("SYBASE_DRIVER", "Adaptive Server Enterprise")
SYBASE_CHARSET = env_str("SYBASE_CHARSET", "BIG5")
SYBASE_TIMEOUT_SEC = env_int("SYBASE_TIMEOUT_SEC", 10)
SYBASE_INI_PATH = env_str("SYBASE_INI_PATH", "")

# ✅ 修正：STATIC_URL 與 MEDIA_URL 不需要手動加 PROXY_PREFIX，因為 FORCE_SCRIPT_NAME 會處理
# 且 Middleware 會剝離 PROXY_PREFIX，Django 內部看到的路徑將不含前綴。
# STATIC_URL = f"{FORCE_SCRIPT_NAME}/static/"
STATIC_URL = f"/static/"
MEDIA_URL = f"/media/"

# 根據環境決定實體路徑
_DEFAULT_STATIC_ROOT = f"{_PROJECT_ROOT_STR}\\staticfiles"
_DEFAULT_MEDIA_ROOT = f"{_PROJECT_ROOT_STR}\\media"

STATIC_ROOT = Path(env_str("STATIC_ROOT", _DEFAULT_STATIC_ROOT))
MEDIA_ROOT = Path(env_str("MEDIA_ROOT", _DEFAULT_MEDIA_ROOT))

# ✅ 修正 staticfiles.W004
_potential_static_dirs = [BASE_DIR / "static"]
STATICFILES_DIRS = [str(p) for p in _potential_static_dirs if p.exists() and p.resolve() != STATIC_ROOT.resolve()]

PIPER_OUTPUT_DIR = MEDIA_ROOT / "tts"
STT_OUTPUT_DIR = MEDIA_ROOT / "stt"

# RAG (PostgreSQL)
RAG_BACKEND = env_str("RAG_BACKEND", "postgres").lower()
RAG_PG_TABLE = env_str("RAG_PG_TABLE", "public.meeting_records")
RAG_TOP_K = env_int("RAG_TOP_K", 10)

# 知識庫與 Mock 資料
API_CONTEXT_PATH = env_str("API_CONTEXT_PATH", f"{_PROJECT_ROOT_STR}\\api\\knowledge\\api.txt")
MOCK_DB_JSON = env_str("MOCK_DB_JSON", f"{_PROJECT_ROOT_STR}\\SQLTEST_output.json")

# ============================================================
# Misc
# ============================================================
TTS_API_BASE_URL = env_str("TTS_API_BASE_URL", "")
TTS_API_TIMEOUT = env_int("TTS_API_TIMEOUT", 60)
OPEN_NOTEBOOK_PORTAL_URL = env_str("OPEN_NOTEBOOK_PORTAL_URL", "http://127.0.0.1:8502")

# ============================================================
# Sybase query workstation whitelist
# ============================================================
DOC_QUERY_ALLOWED_IPS = env_list("DOC_QUERY_ALLOWED_IPS", "127.0.0.1,::1")
DOC_QUERY_TRUST_X_FORWARDED_FOR = env_bool("DOC_QUERY_TRUST_X_FORWARDED_FOR", default=True)

FILE_CHARSET = env_str("FILE_CHARSET", "cp950")
TEXT2PPTX_MAX_CHARS = env_int("TEXT2PPTX_MAX_CHARS", 20000)
TEXT2PPTX_IMAGE_MODE = env_str("TEXT2PPTX_IMAGE_MODE", "mock")
TEXT2PPTX_IMAGE_TIMEOUT_SEC = env_int("TEXT2PPTX_IMAGE_TIMEOUT_SEC", 30)
TEXT2PPTX_IMAGE_RETRY = env_int("TEXT2PPTX_IMAGE_RETRY", 2)
TEXT2PPTX_IMAGE_DIR = env_str("TEXT2PPTX_IMAGE_DIR", str(MEDIA_ROOT / "generated_images" / "text2pptx"))
TEXT2PPTX_IMAGE_PROVIDER_CMD = env_str("TEXT2PPTX_IMAGE_PROVIDER_CMD", "")
TEXT2PPTX_IMAGE_PROVIDER_FALLBACK_CMD = env_str("TEXT2PPTX_IMAGE_PROVIDER_FALLBACK_CMD", "")
TTS_MAX_CHARS = env_int("TTS_MAX_CHARS", 1200)

# 知識庫與 Mock 資料
API_CONTEXT_PATH = env_str("API_CONTEXT_PATH", f"{_PROJECT_ROOT_STR}\\api\\knowledge\\api.txt")
MOCK_DB_JSON = env_str("MOCK_DB_JSON", f"{_PROJECT_ROOT_STR}\\SQLTEST_output.json")

# ============================================================
# Misc
# ============================================================
TTS_API_BASE_URL = env_str("TTS_API_BASE_URL", "")
TTS_API_TIMEOUT = env_int("TTS_API_TIMEOUT", 60)
OPEN_NOTEBOOK_PORTAL_URL = env_str("OPEN_NOTEBOOK_PORTAL_URL", "http://127.0.0.1:8502")

# ============================================================
# Sybase query workstation whitelist
# ============================================================
DOC_QUERY_ALLOWED_IPS = env_list("DOC_QUERY_ALLOWED_IPS", "127.0.0.1,::1")
DOC_QUERY_TRUST_X_FORWARDED_FOR = env_bool("DOC_QUERY_TRUST_X_FORWARDED_FOR", default=True)

FILE_CHARSET = env_str("FILE_CHARSET", "cp950")
TEXT2PPTX_MAX_CHARS = env_int("TEXT2PPTX_MAX_CHARS", 20000)
TEXT2PPTX_IMAGE_MODE = env_str("TEXT2PPTX_IMAGE_MODE", "mock")
TEXT2PPTX_IMAGE_TIMEOUT_SEC = env_int("TEXT2PPTX_IMAGE_TIMEOUT_SEC", 30)
TEXT2PPTX_IMAGE_RETRY = env_int("TEXT2PPTX_IMAGE_RETRY", 2)
TEXT2PPTX_IMAGE_DIR = env_str("TEXT2PPTX_IMAGE_DIR", str(MEDIA_ROOT / "generated_images" / "text2pptx"))
TEXT2PPTX_IMAGE_PROVIDER_CMD = env_str("TEXT2PPTX_IMAGE_PROVIDER_CMD", "")
TEXT2PPTX_IMAGE_PROVIDER_FALLBACK_CMD = env_str("TEXT2PPTX_IMAGE_PROVIDER_FALLBACK_CMD", "")
TTS_MAX_CHARS = env_int("TTS_MAX_CHARS", 1200)
TTS_FILE_MAX_MB = env_int("TTS_FILE_MAX_MB", 15)

# ============================================================
# ✅ Portal Usage Log（維持）
# ============================================================
PORTAL_USAGE_CODE_MAP = [
    ("/", "PORTAL"),
    ("/translator/", "TRANSLATOR"),
    ("/englishchat/", "ENGLISHCHAT"),
    ("/chatbotui/", "CHATBOTUI"),
    ("/comment/", "COMMENT"),
    ("/doc/", "DOC"),
    ("/meetingreply/", "MEETINGREPLY"),
    ("/graph/", "GRAPH"),
    ("/text2pptx/", "TEXT2PPTX"),
    ("/tts/", "TTS"),
    ("/pdf/", "PDF"),
    ("/rag/", "RAG"),
    ("/excelproc/", "EXCELPROC"),
    ("/projectnotes/", "PROJECTNOTES"),
    ("/formalize/", "FORMALIZE"),
    ("/open-notebook/", "OPEN_NOTEBOOK"),
    ("/digital-twin-kb/", "DIGITAL_TWIN_KB"),
]

# ============================================================
# App behavior
# ============================================================
SEED_DOC_TEMPLATES_ON_STARTUP = DEBUG

# ============================================================
# Application definition
# ============================================================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_extensions",
    "webapps.tts.apps.TtsConfig",
    "webapps.common.apps.CommonConfig",
    "webapps.graph2doc.apps.Graph2docConfig",
    "webapps.doc.apps.DocConfig",
    "webapps.text2pptx.apps.Text2PptxConfig",
    "webapps.meetingreply.apps.MeetingreplyConfig",
    "webapps.portal.apps.PortalConfig",
    "webapps.translator.apps.TranslatorConfig",
    "webapps.englishchat.apps.EnglishchatConfig",
    "webapps.chatbotui.apps.ChatbotuiConfig",
    "webapps.todo.apps.TodoConfig",
    "webapps.comment.apps.CommentConfig",
    "webapps.student.apps.StudentConfig",
    "webapps.pdf.apps.PdfConfig",
    "webapps.excelproc.apps.ExcelprocConfig",
    "webapps.rag_oracle.apps.RagOracleConfig",
    "webapps.projectnotes.apps.ProjectnotesConfig",
    "webapps.document_formalize.apps.DocumentFormalizeConfig",
    "webapps.videolearning.apps.VideolearningConfig",
    "webapps.digital_twin_kb.apps.DigitalTwinKbConfig",
    "pgvector.django",
    "django.contrib.postgres",
]

MIDDLEWARE = [
    #'webapps.common.middleware.StaticPathMiddleware',
    # ✅ proxy prefix（依規範：script_name = 唯一真相）
    "webapps.portal.middleware_proxy_prefix.ForwardedPrefixMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",

    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",

    # ✅ IIS bridge
    "webapps.portal.middleware.IISRemoteUserBridgeMiddleware",

    # ✅ Django auth
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.RemoteUserMiddleware",
    "webapps.portal.middleware.ClearRemoteUserMiddleware",

    "webapps.portal.middleware.PortalUsageLogMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.RemoteUserBackend",
    "django.contrib.auth.backends.ModelBackend",
]

ROOT_URLCONF = "webproj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "webapps" / "doc" / "templates",
            BASE_DIR / "webapps" / "digital_twin_kb" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],            
        },
    },
]

WSGI_APPLICATION = "webproj.wsgi.application"

# ============================================================
# Database（Django 本機 auth/設定）
# ============================================================
import os
from urllib.parse import urlparse

DB_URL = os.getenv("DATABASE_URL")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

if DB_URL:
    url = urlparse(DB_URL)
    _pg_config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": url.path[1:],
        "USER": url.username,
        "PASSWORD": url.password,
        "HOST": url.hostname,
        "PORT": url.port or "5432",
    }
    # Mandatory policy: application tables must use PostgreSQL.
    DATABASES["default"] = dict(_pg_config)
    # Keep compatibility for existing ProjectNotes router.
    DATABASES["projectnotes_db"] = dict(_pg_config)

DATABASE_ROUTERS = ["webapps.projectnotes.router.ProjectNotesRouter"]

# ============================================================
# Password validation
# ============================================================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ============================================================
# Internationalization
# ============================================================
LANGUAGE_CODE = "zh-hant"
TIME_ZONE = "Asia/Taipei"
USE_I18N = True
USE_TZ = True

# ============================================================
# ✅ Sessions / Cookies / CSRF（跟 PROXY_PREFIX 走）
# ============================================================
SESSION_COOKIE_SAMESITE = env_str("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = env_str("CSRF_COOKIE_SAMESITE", "Lax")

DEFAULT_COOKIE_PATH = PROXY_PREFIX if PROXY_PREFIX else "/"
SESSION_COOKIE_PATH = env_str("SESSION_COOKIE_PATH", DEFAULT_COOKIE_PATH)
CSRF_COOKIE_PATH = env_str("CSRF_COOKIE_PATH", DEFAULT_COOKIE_PATH)

SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", default=False)

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    "https://mpcai.mpc.mil.tw,http://mpcai.mpc.mil.tw",
)

# ============================================================
# Logging
# ============================================================
LOG_LEVEL = env_str("DJANGO_LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "[{levelname}] {asctime} {name}: {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
    "loggers": {
        "django.security.csrf": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "django.server": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "django.utils.autoreload": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "httpx": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "httpcore": {"handlers": ["console"], "level": "WARNING", "propagate": False},
    },
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
