"""
Django settings for webproj project.
Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# ============================================================
# Base
# ============================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ 讀專案根目錄 .env
load_dotenv(BASE_DIR / ".env")


# ============================================================
# ENV helpers
# ============================================================
def env_bool(key: str, default: bool = False) -> bool:
    v = os.getenv(key, "1" if default else "0")
    v = (v or "").strip().lower()
    return v in ("1", "true", "yes", "y", "on")


def env_int(key: str, default: int) -> int:
    try:
        return int((os.getenv(key) or "").strip() or default)
    except Exception:
        return default


def env_str(key: str, default: str = "") -> str:
    return (os.getenv(key, default) or default).strip()


# ============================================================
# ✅ Portal ACL（入口可看、功能控管）
# ============================================================
PORTAL_ACL_ENABLED = env_bool("PORTAL_ACL_ENABLED", default=False)

# ✅ 新增：ACL backend 選擇（AUTO/ORACLE/DJANGO）
# - AUTO：MODEL_TYPE=OLLAMA => ORACLE；MODEL_TYPE=OPENAI => DJANGO
# - ORACLE：強制使用 Oracle 端的 auth tables 取 groups
# - DJANGO：強制使用本機 Django SQLite 的 auth tables 取 groups
PORTAL_ACL_BACKEND = env_str("PORTAL_ACL_BACKEND", "AUTO").upper()

PORTAL_ACL = {
    # 🔓 入口頁：未登入也可看
    "portal": ["PUBLIC"],

    # 🔐 功能節點：依群組/登入狀態控管
    # 🔓 *value = 允許的 Django Group 名稱清單**
    "translator": ["PUBLIC"],  # 只要登入即可
    "comment": ["PUBLIC", "ADMIN"],
    "doc": ["PUBLIC", "ADMIN"],
    "meeting": ["PUBLIC", "ADMIN"],
    "graph": ["PUBLIC"],
    "pdf": ["PUBLIC"],
    "pptx": ["PUBLIC"],
    "tts": ["PUBLIC"],
    "excelproc": ["PUBLIC","ALL_AUTHENTICATED", "ADMIN"],
    "vanna": ["PUBLIC", "ALL_AUTHENTICATED","ADMIN"],
}


# ============================================================
# Security / Debug
# ============================================================
SECRET_KEY = env_str(
    "DJANGO_SECRET_KEY",
    "django-insecure-u2crmik5h*mugnf1a1)g**vip6&gvd_wjde4k6w2(iu+0z24&%",
)

DEBUG = env_bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = [
    "*",
    "MPCDC.MIL.TW",
    "10.29.136.17",
    "mpcai.mpc.mil.tw",
    "127.0.0.1",
    "localhost",
]


# ============================================================
# CORS
# ============================================================
CORS_ALLOW_ALL_ORIGINS = True


# ============================================================
# OpenAI
# ============================================================
OPENAI_API_KEY = env_str("OPENAI_API_KEY", "")
OPENAI_MODEL = env_str("OPENAI_MODEL", "gpt-4o-mini")
OPENAI_BASE_URL = env_str("OPENAI_BASE_URL", "https://api.openai.com")
OPENAI_TIMEOUT = env_int("OPENAI_TIMEOUT", 60)


# ============================================================
# Ollama / 舊模型設定
# ============================================================
MODEL_BASE_URL = env_str("MODEL_BASE_URL", "http://mpcai.mpc.mil.tw:11434")
MODEL_APR_KEY = env_str("MODEL_APR_KEY", "")
MODEL_NAME = env_str("MODEL_NAME", "magistral-small")
MODEL_TIMEOUT = env_int("MODEL_TIMEOUT", 120)
USE_OLLAMA_FIRST = env_bool("USE_OLLAMA_FIRST", default=True)

LANGCHAIN = {
    "MODEL": "ollama",
    "Ollama": {
        "model": env_str("LANGCHAIN_OLLAMA_MODEL", "mistral_small_3_1_2503:latest"),
        "temperature": float(env_str("LANGCHAIN_TEMPERATURE", "0.7") or "0.7"),
    },
}

# ============================================================
# MODEL_TYPE（你既有邏輯）
# ============================================================
# 外網 .env：MODEL_TYPE=OPENAI
# 內網 .env：MODEL_TYPE=OLLAMA
MODEL_TYPE = env_str("MODEL_TYPE", "OLLAMA").upper()

# views.py 統一讀 OLLAMA_BASE_URL（沿用 MODEL_BASE_URL，不破壞舊系統）
OLLAMA_BASE_URL = env_str("OLLAMA_BASE_URL", MODEL_BASE_URL)
OLLAMA_BASE_URL_EXTERNAL = env_str("OLLAMA_BASE_URL_EXTERNAL", "")


# ============================================================
# ✅ Oracle（給 excelproc + ACL(ORACLE) 共用）
# ============================================================
# 會由 acl.py / excelproc/services.py 使用（建議全部從 .env 讀）
ORA_HOST = env_str("ORA_HOST", "10.29.136.198")
ORA_PORT = env_int("ORA_PORT", 1521)
ORA_SERVICE_NAME = env_str("ORA_SERVICE_NAME", "mpcdb6198")
ORA_USER = env_str("ORA_USER", "smcadm")
ORA_PASS = env_str("ORA_PASS", "mpcdbadm")


# ============================================================
# Media / Piper / Whisper
# ============================================================
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

PIPER_OUTPUT_DIR = MEDIA_ROOT / "tts"

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

WHISPER_EXE = BASE_DIR / "whispercpp" / "whisper-cli.exe"
WHISPER_MODEL = BASE_DIR / "whispercpp" / "models" / "ggml-medium.bin"

STT_OUTPUT_DIR = MEDIA_ROOT / "stt"
TTS_API_BASE_URL = env_str("TTS_API_BASE_URL", "")
TTS_API_TIMEOUT = env_int("TTS_API_TIMEOUT", 60)

FILE_CHARSET = env_str("FILE_CHARSET", "cp950")  # cp950 / big5

# text2pptx
TEXT2PPTX_MAX_CHARS = env_int("TEXT2PPTX_MAX_CHARS", 20000)

# tts
TTS_MAX_CHARS = env_int("TTS_MAX_CHARS", 1200)
TTS_FILE_MAX_MB = env_int("TTS_FILE_MAX_MB", 15)


# ============================================================
# App behavior
# ============================================================
SEED_DOC_TEMPLATES_ON_STARTUP = DEBUG


# ============================================================
# Application definition
# ============================================================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "corsheaders",
    "django_extensions",

    # Local apps
    "webapps.tts.apps.TtsConfig",
    "webapps.graph2doc.apps.Graph2docConfig",
    "webapps.doc.apps.DocConfig",
    "webapps.text2pptx.apps.Text2PptxConfig",
    "webapps.meetingreply.apps.MeetingreplyConfig",
    "webapps.portal.apps.PortalConfig",
    "webapps.translator.apps.TranslatorConfig",
    "webapps.comment.apps.CommentConfig",
    "webapps.student.apps.StudentConfig",
    "webapps.pdf.apps.PdfConfig",
    "webapps.excelproc.apps.ExcelprocConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",

    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "webproj.urls"

# ============================================================
# Templates（✅ request context_processor 只放一份）
# ============================================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django.context_processors.global_vars',  # 添加这个
            ],
        },
    },
]

WSGI_APPLICATION = "webproj.wsgi.application"


# ============================================================
# Database
# ============================================================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ============================================================
# Password validation
# ============================================================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ============================================================
# Internationalization
# ============================================================
LANGUAGE_CODE = "zh-hant"
TIME_ZONE = "Asia/Taipei"
USE_I18N = True
USE_TZ = True


# ============================================================
# Default primary key field type
# ============================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
