# Generated by Django 6.0 on 2026-01-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateField(db_index=True, verbose_name='使用日期')),
                ('program_code', models.CharField(db_index=True, max_length=50, verbose_name='程式代碼')),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='使用者代碼')),
                ('user_name', models.CharField(blank=True, default='', max_length=128, verbose_name='使用者姓名')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='請求路徑')),
                ('method', models.CharField(blank=True, default='GET', max_length=10, verbose_name='HTTP 方法')),
                ('ip', models.CharField(blank=True, default='', max_length=64, verbose_name='來源 IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': 'Portal 使用紀錄',
                'verbose_name_plural': 'Portal 使用紀錄',
                'db_table': 'portal_usage_log',
                'ordering': ['-used_date', '-created_at'],
                'indexes': [models.Index(fields=['used_date', 'program_code'], name='portal_usag_used_da_08772d_idx'), models.Index(fields=['user_id'], name='portal_usag_user_id_585d75_idx')],
                'constraints': [models.UniqueConstraint(fields=('used_date', 'program_code', 'user_id'), name='uq_portal_usage_per_day')],
            },
        ),
    ]
