# Generated by Django 6.0 on 2026-01-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portalusagelog',
            name='uq_portal_usage_per_day',
        ),
    ]
