# Generated by Django 6.0 on 2026-03-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_portalusagelog_uq_portal_usage_per_day'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portalusagelog',
            new_name='ix_pul_date_code',
            old_name='portal_usag_used_da_08772d_idx',
        ),
        migrations.RenameIndex(
            model_name='portalusagelog',
            new_name='ix_pul_user',
            old_name='portal_usag_user_id_585d75_idx',
        ),
        migrations.AddField(
            model_name='portalusagelog',
            name='whoami_json',
            field=models.TextField(blank=True, default='{}', verbose_name='WhoAmI 資訊'),
        ),
        migrations.AddIndex(
            model_name='portalusagelog',
            index=models.Index(fields=['program_code'], name='ix_pul_code'),
        ),
    ]
