with open('webapps/projectnotes/models.py', 'a', encoding='utf-8') as f:
    f.write('\nclass ProcessingJob(models.Model):\n')
    f.write('    """Background task tracking for ingestion/vectorization."""\n\n')
    f.write('    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="jobs")\n')
    f.write('    job_type = models.CharField(max_length=50) # "source_ingestion", "project_rebuild"\n')
    f.write('    status = models.CharField(max_length=20, default="pending") # pending, processing, completed, failed\n')
    f.write('    target_id = models.PositiveIntegerField(null=True, blank=True)\n')
    f.write('    progress_info = models.TextField(blank=True, default="")\n')
    f.write('    error_message = models.TextField(blank=True, default="")\n')
    f.write('    created_at = models.DateTimeField(auto_now_add=True)\n')
    f.write('    updated_at = models.DateTimeField(auto_now=True)\n\n')
    f.write('    class Meta:\n')
    f.write('        app_label = "projectnotes"\n')
    f.write('        db_table = "projectnotes_processing_job"\n')
