-- 電子來文附件
SELECT EM.EM_GRSNO, EF.EF_NAME, EF.EF_DATA, EF.EF_PAGE
FROM mnda.dbo.DCS1_EMAL_TMP EM
LEFT JOIN mnda.dbo.DCS1_EMAL_FILE EF ON EM.EM_FID = EF.EF_ID
WHERE EM.EM_GRSNO = :AS_EM_GRSNO;

SELECT EM.EM_GRSNO, EM.EM_FID
FROM mnda.dbo.DCS1_EMAL_TMP EM
WHERE EM.EM_GRSNO = :AS_EM_GRSNO;

SELECT EM.EM_GRSNO, EM.EM_FID
FROM mnda.dbo.DCS1_EMAL_TMP EM
WHERE EM.EM_GRSNO = :AS_EM_GRSNO;

SELECT EM.EM_GRSNO, EM.EM_PSID
FROM mnda.dbo.DCS1_EMAL_TMP EM
WHERE EM.EM_GRSNO = :AS_EM_GRSNO;

(1) 的筆數與 EF_NAME/EF_PAGE
(2) 的 EM_FID 是否有值
(3) 的筆數（是否跟 (1) 相同）
(4) 的 EM_PSID 是否等於 F129195600